export const BSC_CHAIN_ID = 56;
export const BSC_RPC = "https://bsc-dataseed1.binance.org";
export const BSC_RPCS = [
  BSC_RPC,
  "https://bsc-dataseed2.binance.org",
  "https://bsc-dataseed3.binance.org",
  "https://bsc-dataseed4.binance.org",
];

export const USDT_ADDRESS = "0x55d398326f99059fF775485246999027B3197955";

// ── Platform contracts (deployed once, shared by all markets) ────────────────
// Fill in addresses after running the FFX deploy script on BSC mainnet.
// Trading UI unlocks automatically once FACTORY is set.
export const FFX_CONTRACTS = {
  PLATFORM:   "0xfEE26fe6E12802DE7eeD3587dc0DF71400377EA5", // FFXPlatform.sol
  ORACLE:     "0xBB4859Dca435fE68f78d6Aa647e75aD8a4fDAD6F", // FFXOracle.sol
  FUNDING:    "0x551355B2998787EE963aC842252c87Afc5936bfE", // FFXFunding.sol
  FACTORY:    "0xb86D9ae5321A2006788Ea5844C30064C57bE34CE", // FFXFactory.sol
  VAULT_IMPL: "0x082d3051eCED166849EC138BB2E8662054e0d9db", // FFXVault.sol implementation (EIP-1167 clone target)
  PERPS_IMPL: "0xcf0c15A14062529b208229Fc4B8665eBa8FB5828", // FFXPerps.sol implementation (EIP-1167 clone target)
} as const;

// Platform bot operator wallet (generates per-market wallets via Factory)
export const PLATFORM_BOT_WALLET = "";

// FFX platform token PancakeSwap pool — set once liquidity is deployed
export const FLAP_PANCAKE_POOL = "";

// Alias used by apply.tsx — maps to the shared FFXPlatform contract
export const FLAP_PLATFORM_ADDRESS = FFX_CONTRACTS.PLATFORM;

// ── Deployment state ────────────────────────────────────────────────────────
// Automatically true once FFX_CONTRACTS.FACTORY has a real address.
// Do NOT hardcode to `true` — that would enable the trading UI with no contracts.
export const CONTRACTS_DEPLOYED = Boolean(FFX_CONTRACTS.FACTORY);

// ── Architecture ──────────────────────────────────────────────────────────────
//
//  PLATFORM (deployed once):
//    FFXOracle   — shared price feed; platform bot + per-market bots can push
//    FFXFunding  — shared 8h funding settlement across all markets
//    FFXFactory  — deploys FFXVault + FFXPerps clone pairs per market
//                  also registers per-market bot in Oracle
//    FFXPlatform — admin: pause/unpause markets, emergency withdraw
//
//  PER-MARKET (deployed by FFXFactory.createMarket):
//    FFXVault    — holds USDT collateral; insurance min = 20% of vault
//    FFXPerps    — trading: market + limit orders, cross/isolated, TP/SL
//    botWallet   — dedicated wallet generated by platform for that market
//

// ── ABIs ─────────────────────────────────────────────────────────────────────

export const USDT_ABI = [
  "function approve(address spender, uint256 amount) external returns (bool)",
  "function allowance(address owner, address spender) external view returns (uint256)",
  "function balanceOf(address account) external view returns (uint256)",
  "function decimals() external view returns (uint8)",
  "function transfer(address to, uint256 amount) external returns (bool)",
];

// FFXVault.sol
export const VAULT_ABI = [
  "function depositVault(uint256 amount) external",
  "function depositInsurance(uint256 amount) external",
  "function requestWithdrawal() external",
  "function completeWithdrawal() external",
  "function checkHealth() external",
  "function emergencyWithdraw(address to) external",
  "function setPlatformContract(address p) external",
  // Views
  "function vaultBalance() external view returns (uint256)",
  "function insuranceBalance() external view returns (uint256)",
  "function minInsuranceRequired() external view returns (uint256)",
  "function hasMinInsurance() external view returns (bool)",
  "function vaultLockedUntil() external view returns (uint256)",
  "function lockDuration() external view returns (uint256)",
  "function marketClosed() external view returns (bool)",
  "function isFrozen() external view returns (bool)",
  "function isWithdrawable() external view returns (bool)",
  "function isWithdrawalBlocked() external view returns (bool)",
  "function withdrawalRequested() external view returns (bool)",
  "function trustBadge() external view returns (uint8)",
  "function trustBadgeName() external view returns (string)",
  "function opener() external view returns (address)",
  "function botWallet() external view returns (address)",
  "function frozenAt() external view returns (uint256)",
  "function minVault() external view returns (uint256)",
];

// FFXPerps.sol — per-market trading engine with Cross/Isolated, TP/SL, Limit
export const PERPS_ABI = [
  // Market orders — marginMode: 0=ISOLATED, 1=CROSS
  "function openPosition(uint256 margin, uint8 leverage, bool isLong, uint8 marginMode, uint256 tpPrice, uint256 slPrice) external",
  "function closePosition(uint256 positionId) external",
  "function liquidate(uint256 positionId) external",
  // TP/SL
  "function setTpSl(uint256 positionId, uint256 tpPrice, uint256 slPrice) external",
  "function executeTpSl(uint256 positionId) external",
  // Limit orders
  "function placeLimitOrder(uint256 margin, uint8 leverage, bool isLong, uint256 limitPrice, uint8 marginMode, uint256 tpPrice, uint256 slPrice) external",
  "function executeLimitOrder(uint256 orderId) external",
  "function cancelLimitOrder(uint256 orderId) external",
  // Cross margin
  "function depositCross(uint256 amount) external",
  "function withdrawCross(uint256 amount) external",
  "function crossBalance(address trader) external view returns (uint256)",
  // Opener fee claim
  "function claimFees() external",
  // Position reads
  "function getPosition(uint256 positionId) external view returns (address trader, uint256 margin, uint8 leverage, bool isLong, uint256 entryPrice, uint256 size, uint256 openedAt, bool isOpen, int256 fundingAccrued, uint8 marginMode, uint256 tpPrice, uint256 slPrice)",
  "function traderPositions(address trader) external view returns (uint256[])",
  "function getUnrealizedPnl(uint256 positionId) external view returns (int256)",
  "function isLiquidatable(uint256 positionId) external view returns (bool)",
  // Limit order reads
  "function getLimitOrder(uint256 orderId) external view returns (address trader, uint256 margin, uint8 leverage, bool isLong, uint256 limitPrice, uint8 marginMode, uint256 tpPrice, uint256 slPrice, bool filled, bool cancelled, uint256 createdAt)",
  "function traderLimitOrders(address trader) external view returns (uint256[])",
  // Market stats
  "function getCurrentParams() external view returns (uint256 spread, uint8 maxLeverage, uint256 maxPosition, uint256 maxOI, uint256 currentOI)",
  "function getLongRatio() external view returns (uint256)",
  "function getTotalOI() external view returns (uint256)",
  "function getOpenPositionCount() external view returns (uint256)",
  "function pendingOpenerFees() external view returns (uint256)",
  "function totalLongOI() external view returns (uint256)",
  "function totalShortOI() external view returns (uint256)",
  "function openPositionCount() external view returns (uint256)",
  "function nextPositionId() external view returns (uint256)",
  "function nextLimitOrderId() external view returns (uint256)",
  // Config reads
  "function opener() external view returns (address)",
  "function botWallet() external view returns (address)",
  "function platformFeeWallet() external view returns (address)",
  "function emergencyPaused() external view returns (bool)",
  // Platform
  "function emergencyPause() external",
  "function emergencyUnpause() external",
  "function emergencyDrain(address to) external",
  "function setPlatformContract(address p) external",
  "function platformContract() external view returns (address)",
  "function TRADE_FEE_BPS() external view returns (uint256)",
  "function MIN_TRADE_FEE() external view returns (uint256)",
  "function LIQ_THRESHOLD_BPS() external view returns (uint256)",
];

// FFXOracle.sol — shared, platform bot + per-market bots push prices
export const ORACLE_ABI = [
  "function updatePrice(address token, uint256 price, uint256 mcap, uint256 liquidity) external",
  "function updatePriceBatch(address[] calldata tokens, uint256[] calldata prices, uint256[] calldata mcaps, uint256[] calldata liquidities) external",
  "function setTokenBot(address token, address bot) external",
  "function setFactory(address factory) external",
  "function getPrice(address token) external view returns (uint256)",
  "function getMcap(address token) external view returns (uint256)",
  "function getFeed(address token) external view returns (uint256 price, uint256 mcap, uint256 liquidity, uint256 updatedAt, bool isStale)",
  "function isFresh(address token) external view returns (bool)",
  "function platformBot() external view returns (address)",
  "function tokenBot(address token) external view returns (address)",
  "function factory() external view returns (address)",
  "function initiatePlatformBotTransfer(address newBot) external",
  "function acceptPlatformBotTransfer() external",
];

// FFXFunding.sol — shared, platform bot settles every 8h per market
export const FUNDING_ABI = [
  "function settle(address perps) external",
  "function registerMarket(address perps) external",
  "function setFactory(address factory) external",
  "function setPlatformContract(address p) external",
  "function markets(address perps) external view returns (uint256 lastSettled, bool registered)",
  "function platformBot() external view returns (address)",
  "function factory() external view returns (address)",
];

// FFXFactory.sol — deploys Vault+Perps clone pairs, registers per-market bots
export const FACTORY_ABI = [
  "function createMarket(address token, address opener, address botWallet, uint256 lockDuration, uint256 minVault) external returns (address vault, address perps)",
  "function markets(address token) external view returns (address vault, address perps, address botWallet, bool exists)",
  "function setOracle(address oracle) external",
  "function setFunding(address funding) external",
  "function setPlatformContract(address p) external",
  "function setImpls(address vault, address perps) external",
  "function transferAdmin(address newAdmin) external",
  "function admin() external view returns (address)",
  "function oracle() external view returns (address)",
  "function funding() external view returns (address)",
  "function vaultImpl() external view returns (address)",
  "function perpsImpl() external view returns (address)",
];

// FFXPlatform.sol — admin controls
export const PLATFORM_ABI = [
  "function pauseMarket(address perps) external",
  "function unpauseMarket(address perps) external",
  "function emergencyWithdrawAll(address[] calldata vaults, address[] calldata perps, address to) external",
  "function setOracle(address oracle) external",
  "function setFunding(address funding) external",
  "function setFactory(address factory) external",
  "function transferAdmin(address newAdmin) external",
  "function admin() external view returns (address)",
  "function oracle() external view returns (address)",
  "function funding() external view returns (address)",
  "function factory() external view returns (address)",
];
