// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title FFXFactory — deploys FFXVault + FFXPerps clone pairs per market.
/// Also registers the per-market bot wallet in the shared Oracle
/// and registers the new Perps contract in FFXFunding for 8-hour settlement.
contract FFXFactory {

    address public admin;
    address public oracle;
    address public funding;
    address public platformContract;
    address public platformFeeWallet;
    address public vaultImpl;
    address public perpsImpl;
    address public collateral; // USDT

    struct Market {
        address vault;
        address perps;
        address botWallet;
        bool    exists;
    }

    mapping(address => Market) public markets; // token => Market

    event MarketCreated(
        address indexed token,
        address indexed opener,
        address vault,
        address perps,
        address botWallet
    );
    event ImplsUpdated(address vault, address perps);

    modifier onlyAdmin() {
        require(msg.sender == admin, "FFXFactory: not admin");
        _;
    }

    constructor(
        address _admin,
        address _oracle,
        address _funding,
        address _platformFeeWallet,
        address _vaultImpl,
        address _perpsImpl,
        address _collateral
    ) {
        require(_admin != address(0) && _oracle != address(0), "FFXFactory: zero");
        admin             = _admin;
        oracle            = _oracle;
        funding           = _funding;
        platformFeeWallet = _platformFeeWallet;
        vaultImpl         = _vaultImpl;
        perpsImpl         = _perpsImpl;
        collateral        = _collateral;
    }

    /// @notice Deploy Vault + Perps for a new market.
    /// @param token         The meme token address
    /// @param opener        Market creator address
    /// @param botWallet     Dedicated bot wallet generated by platform for this market
    /// @param lockDuration  Lock period (7/30/90/180 days in seconds)
    /// @param minVault      Minimum vault requirement in USDT (18 dec)
    function createMarket(
        address token,
        address opener,
        address botWallet,
        uint256 lockDuration,
        uint256 minVault
    ) external onlyAdmin returns (address vault, address perps) {
        require(token != address(0) && opener != address(0) && botWallet != address(0), "FFXFactory: zero");
        require(!markets[token].exists, "FFXFactory: market exists");

        // Deploy minimal proxy (EIP-1167) for Vault
        vault = _clone(vaultImpl);
        IFFXVaultInit(vault).initialize(
            opener,
            token,
            collateral,
            oracle,
            address(this),
            lockDuration,
            admin,
            minVault,
            botWallet
        );

        // Deploy minimal proxy (EIP-1167) for Perps
        perps = _clone(perpsImpl);
        IFFXPerpsInit(perps).initialize(
            token,
            collateral,
            vault,
            oracle,
            funding,
            opener,
            platformFeeWallet,
            botWallet,
            address(this)
        );

        // Link vault ↔ perps
        IFFXVaultLink(vault).setPerps(perps);
        IFFXVaultLink(vault).setPlatformContract(platformContract);
        IFFXPerpsLink(perps).setPlatformContract(platformContract);

        // Register per-market bot in shared Oracle
        IFFXOracle(oracle).setTokenBot(token, botWallet);

        // Register Perps in FFXFunding for 8-hour settlement
        if (funding != address(0)) {
            IFFXFunding(funding).registerMarket(perps);
        }

        markets[token] = Market(vault, perps, botWallet, true);

        emit MarketCreated(token, opener, vault, perps, botWallet);
    }

    function setPlatformContract(address _p) external onlyAdmin {
        require(_p != address(0), "FFXFactory: zero");
        platformContract = _p;
    }

    function setOracle(address _o) external onlyAdmin {
        require(_o != address(0), "FFXFactory: zero");
        oracle = _o;
    }

    function setFunding(address _f) external onlyAdmin {
        require(_f != address(0), "FFXFactory: zero");
        funding = _f;
    }

    function setImpls(address _vault, address _perps) external onlyAdmin {
        vaultImpl = _vault;
        perpsImpl = _perps;
        emit ImplsUpdated(_vault, _perps);
    }

    function transferAdmin(address newAdmin) external onlyAdmin {
        require(newAdmin != address(0), "FFXFactory: zero");
        admin = newAdmin;
    }

    /// @dev EIP-1167 minimal proxy clone
    function _clone(address impl) internal returns (address instance) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, 0x3d602d80600a3d3981f3363d3d373d3d3d363d73000000000000000000000000)
            mstore(add(ptr, 0x14), shl(0x60, impl))
            mstore(add(ptr, 0x28), 0x5af43d82803e903d91602b57fd5bf30000000000000000000000000000000000)
            instance := create(0, ptr, 0x37)
        }
        require(instance != address(0), "FFXFactory: clone failed");
    }
}

interface IFFXVaultInit {
    function initialize(
        address opener, address token, address collateral, address oracle,
        address factory, uint256 lockDuration, address platformAdmin,
        uint256 minVault, address botWallet
    ) external;
}

interface IFFXVaultLink {
    function setPerps(address perps) external;
    function setPlatformContract(address p) external;
}

interface IFFXPerpsInit {
    function initialize(
        address token, address collateral, address vault, address oracle,
        address funding, address opener, address pfw, address botWallet, address factory
    ) external;
}

interface IFFXPerpsLink {
    function setPlatformContract(address p) external;
}

interface IFFXOracle {
    function setTokenBot(address token, address bot) external;
}

interface IFFXFunding {
    function registerMarket(address perps) external;
}
